const express=require('express')
const app=express()
app.set('view engine', 'ejs')
app.use(express.static('js'))
app.use(express.static('css'))
app.use(express.static('images'))
app.get("/",(req,res)=>{
    res.render('index')
})
app.listen(3000)