version: "3.7"

services:
  rapp:
    container_name: react
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./rapp:/app"
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true